/**
 * fetch-fonts.mjs
 *
 * Self-hosts the three brand faces instead of relying on a runtime font CDN.
 *
 * Why not a font module: it needs `fonts.google.com/metadata/fonts` to
 * enumerate families, and self-hosting removes a third-party request from the
 * critical path anyway — no extra DNS/TLS handshake before text can paint, and
 * no dependency on Google being reachable from wherever this is built.
 *
 * Fetches the css2 API as a modern browser (so we get woff2), keeps only the
 * subsets this site actually sets type in, downloads each file into
 * public/fonts, and writes app/assets/css/fonts.css with the rewritten
 * @font-face rules.
 *
 * Run: node scripts/fetch-fonts.mjs
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const OUT_DIR = path.resolve(process.cwd(), "public/fonts");
const CSS_OUT = path.resolve(process.cwd(), "app/assets/css/fonts.css");

/** Chrome UA — Google serves woff2 only to browsers it recognises. */
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

/** Azerbaijani lives in latin-ext; Russian in cyrillic. */
const KEEP_SUBSETS = new Set(["latin", "latin-ext", "cyrillic"]);

const FAMILIES = [
  { name: "Prata", spec: "Prata:wght@400" },
  { name: "Playfair Display", spec: "Playfair+Display:ital,wght@0,400;0,500;1,400;1,500" },
  { name: "Inter", spec: "Inter:wght@400;500" },
];

/** Google precedes each @font-face with a `/* subset *\/` comment. */
function parseFaces(css) {
  const out = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi;
  let m;
  while ((m = re.exec(css))) out.push({ subset: m[1], block: m[2] });
  return out;
}

async function run() {
  await mkdir(OUT_DIR, { recursive: true });

  const chunks = [
    "/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n",
  ];
  let downloaded = 0;

  for (const family of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?family=${family.spec}&display=swap`;
    const res = await fetch(url, { headers: { "User-Agent": UA } });
    if (!res.ok) throw new Error(`${family.name}: css2 responded ${res.status}`);

    const css = await res.text();
    const faces = parseFaces(css);
    if (!faces.length) throw new Error(`${family.name}: no @font-face blocks parsed`);

    let kept = 0;

    for (const face of faces) {
      if (!KEEP_SUBSETS.has(face.subset)) continue;

      const srcMatch = face.block.match(/url\((https:\/\/[^)]+\.woff2)\)/);
      if (!srcMatch) continue;

      const fileUrl = srcMatch[1];
      const weight = face.block.match(/font-weight:\s*(\d+)/)?.[1] ?? "400";
      const style = /font-style:\s*italic/.test(face.block) ? "italic" : "normal";
      const slug = family.name.toLowerCase().replace(/\s+/g, "-");
      const filename = `${slug}-${weight}-${style}-${face.subset}.woff2`;

      const fontRes = await fetch(fileUrl, { headers: { "User-Agent": UA } });
      if (!fontRes.ok) throw new Error(`${filename}: ${fontRes.status}`);

      await writeFile(
        path.join(OUT_DIR, filename),
        Buffer.from(await fontRes.arrayBuffer()),
      );
      downloaded++;
      kept++;

      // Keep the unicode-range: it is what lets the browser skip downloading
      // Cyrillic for an English visitor, and it drives the per-glyph fallback
      // from Prata to Playfair for Azerbaijani.
      chunks.push(
        face.block
          .replace(/url\(https:\/\/[^)]+\.woff2\)/, `url('/fonts/${filename}')`)
          .replace(/@font-face\s*\{/, "@font-face {\n  font-display: swap;")
          .trim(),
      );
    }

    console.log(`✓ ${family.name} — ${kept} faces`);
  }

  await writeFile(CSS_OUT, chunks.join("\n\n") + "\n");
  console.log(`\n${downloaded} files → public/fonts`);
  console.log(`stylesheet → ${path.relative(process.cwd(), CSS_OUT)}`);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
